### ISSUE TITLE
Crash when temperature regulator is in inventory

### ISSUE THREAD

**Issue by Luke616** [p455w0rd/ToughExpansion#7]
Title, using tough expansion 3.0.8, TAN 2.1.0.51, and forge 2345. This is on MC 1.11.2

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.11.2-2.1.0.51-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/25/17 4:06 PM
Description: Ticking player

java.lang.NoSuchFieldError: ENABLE_TEMPERATURE
	at p455w0rd.tanaddons.items.ItemTempRegulator.doTick(ItemTempRegulator.java:67)
	at p455w0rd.tanaddons.items.ItemTempRegulator.func_77663_a(ItemTempRegulator.java:153)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:423)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:514)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at p455w0rd.tanaddons.items.ItemTempRegulator.doTick(ItemTempRegulator.java:67)
	at p455w0rd.tanaddons.items.ItemTempRegulator.func_77663_a(ItemTempRegulator.java:153)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:423)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:514)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 755
	Entity Name: Luke616
	Entity's Exact location: 172.63, 69.00, 296.12
	Entity's Block location: World: (172,69,296), Chunk: (at 12,4,8 in 10,18; contains blocks 160,0,288 to 175,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@147d7de2
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 910603696 bytes (868 MB) / 1870135296 bytes (1783 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2345 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2345.jar) 
	UCHIJAAAA	forge{13.20.0.2345} [Minecraft Forge] (forge-1.11.2-13.20.0.2345.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.15} [p455w0rd's Library] (p455w0rdslib-1.11.2-1.0.15.jar) 
	UCHIJAAAA	toughasnails{2.1.0.51} [Tough As Nails] (ToughAsNails-1.11.2-2.1.0.51-universal.jar) 
	UCHIJAAAA	tanaddons{3.0.8} [Tough Expansion] (ToughExpansion-1.11.2-3.0.8.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.11.2-2.1.0.51-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Luke616'/755, l='New World', x=172.63, y=69.00, z=296.12]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by p455w0rd** [comment]
TAN must've updated and moved that variable..thanks for the report!

**Comment by p455w0rd** [comment]
- Go to [the download page](https://minecraft.curseforge.com/projects/tough-expansion/files).
- Get [ToughExpansion-1.11.2-3.0.9.jar](https://minecraft.curseforge.com/projects/tough-expansion/files/2441644/download).
- Be satisfy? :+1:
