### ISSUE TITLE
Tempregulator not initilize correctly

### ISSUE THREAD

**Issue by ghost** [p455w0rd/ToughExpansion#9]
Hello,

everytime I started my forever stranded server, I get this error message. It seems not to influence the correct running, of my server, but its just an error.

11:05:42] [Server thread/ERROR] [FML/]: A TileEntity tanaddons:tempregulator(p455w0rd.tanaddons.tiles.TileTempRegulator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
at p455w0rd.tanaddons.tiles.TileTempRegulator.func_145839_a(TileTempRegulator.java:164) ~[TileTempRegulator.class:?]
at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Regards,
Karsten

**Comment by p455w0rd** [comment]
mc version?

**Comment by p455w0rd** [comment]
no reply..I've added code to try and fix this, but without you around to test I have no clue if it works and it's for the 1.11.2 version so I don't even know if the version is correct..so here's to hoping

**Comment by Nightcaste** [comment]
I am having the exact same issue in Forever Stranded.  MC version is 1.10.2, ToughExpansion version 1.0.4

**Comment by p455w0rd** [comment]
pls join my discord: https://discord.gg/9J7yhUP
